bindings:
  - name: kubemq-query-mqtt
    source:
      kind: source.query
      name: kubemq-query
      properties:
        address: "kubemq-cluster:50000"
        client_id: "kubemq-query-mqtt-connector"
        auth_token: ""
        channel: "query.mqtt"
        group:   ""
        auto_reconnect: "true"
        reconnect_interval_seconds: "1"
        max_reconnects: "0"
    target:
      kind: target.messaging.mqtt
      name: target-mqtt
      properties:
        host: "localhost:1883"
        username: "username"
        password: "password"
        client_id: "client_id"
    properties:
      log_level: "error"
