bindings:
  - name: kubemq-query-minio
    source:
      kind: source.query
      name: kubemq-query
      properties:
        host: "localhost"
        port: "50000"
        client_id: "kubemq-query-minio-connector"
        auth_token: ""
        channel: "query.minio"
        group:   ""
        concurrency: "1"
        auto_reconnect: "true"
        reconnect_interval_seconds: "1"
        max_reconnects: "0"
    target:
      kind: target.storage.minio
      name: target-minio
      properties:
        endpoint: "localhost:9001"
        use_ssl: "true"
        access_key_id: "minio"
        secret_access_key: "minio123"
