bindings:
  - name: kubemq-query-redshift
    source:
      kind: kubemq.query
      name: kubemq-query
      properties:
        address: "kubemq-cluster:50000"
        client_id: "kubemq-query-redshift-connector"
        auth_token: ""
        channel: "query.rds.redshift"
        group:   ""
        auto_reconnect: "true"
        reconnect_interval_seconds: "1"
        max_reconnects: "0"
    target:
      kind:aws.rds.redshift
      name: target-aws-rds-redshift
      properties:
        connection: "sslmode=require user=myuser password=mypass host=myhost port=5439 dbname=redshiftdb"
        max_idle_connections: "10"
        max_open_connections: "100"
        connection_max_lifetime_seconds: "3600"
