bindings:
  - name: kubemq-query-gcp-bigquery
    source:
      kind: source.query
      name: kubemq-query
      properties:
        address: "kubemq-cluster:50000"
        client_id: "kubemq-query-gcp-bigquery-connector"
        auth_token: ""
        channel: "query.gcp.bigquery"
        group:   ""
        auto_reconnect: "true"
        reconnect_interval_seconds: "1"
        max_reconnects: "0"
    target:
      kind: target.gcp.bigquery
      name: target-gcp-bigquery
      properties:
        project_id: "id"
        credentials: 'json'
