bindings:
  - name: kubemq-query-aws-mariadb
    source:
      kind: kubemq.query
      name: kubemq-query
      properties:
        address: "kubemq-cluster:50000"
        client_id: "kubemq-query-aws-mariadb-connector"
        auth_token: ""
        channel: "query.aws.mariadb"
        group: ""
        auto_reconnect: "true"
        reconnect_interval_seconds: "1"
        max_reconnects: "0"
    target:
      kind:aws.rds.mariadb
      name: aws-rds-mariadb
      properties:
        connection: "root:mysql@(localhost:3306)/store?charset=utf8&parseTime=True&loc=Local"
        max_idle_connections: "10"
        max_open_connections: "100"
        connection_max_lifetime_seconds: "3600"
